services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9102:9102"  
      - "9101:9101" 
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9011"
    volumes:
      # TODO: switch location later
      - /Users/azzura/Documents/minio

volumes:
  minio_data:
