run-docker-kafka:
	docker-compose -f docker-compose.kafka.yaml up -d

stop-docker-kafka:
	docker-compose -f docker-compose.kafka.yaml down

run-docker-log:
	docker-compose -f docker-compose.log.yaml up -d

stop-docker-log:
	docker-compose -f docker-compose.log.yaml down